django_defaults/core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'delete-contact/(?P<contact_id>[0-9]+)$', views.delete_contact,
        name="delete-contact"),
    url(r'call/(?P<contact_id>[0-9]+)$', views.call, name="call-contact"),
    url(r'conference-twiml$', views.conference_twiml, name="conference-twiml"),
    url(r'$', views.contacts, name="contacts"),
]

django_defaults/django_defaults/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^mattmakai/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
]

django_defaults/core/models.py
from django.db import models


class Contact(models.Model):
    """
        Represents a single person that can be contacted by our app.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=32)

    def __unicode__(self):
        return '<Contact {0} {1} {2}>'.format(self.first_name,
                                              self.last_name,
                                              self.phone_number)

django_defaults/core/forms.py
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Contact


class ContactForm(ModelForm):
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Save', 'save', css_class='btn-primary'))

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'phone_number']

django_defaults/core/views.py
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from twilio import twiml
from twilio.rest import TwilioRestClient

from .forms import ContactForm
from .models import Contact


client = TwilioRestClient()


def contacts(request):
    if request.method == 'GET':
        contacts = Contact.objects.all()
        form = ContactForm()
        return render(request, 'contacts.html', {"contacts": contacts,
                                                 'form': form})
    elif request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # save valid form object
            form.save()
            return redirect('core:contacts')
        return render(request, 'contacts.html', {"form": form})


def delete_contact(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    contact.delete()
    return redirect('core:contacts')


def call(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    client.calls.create(to=contact.phone_number, from_=settings.TWILIO_NUMBER,
                        url="http://twimlbin.com/external/5433e2a6577fdbf5")
    return redirect('core:contacts')


def conference_twiml(request):
    twiml_response = twiml.Response()
    twiml_response.dial().conference('pycontacts')
    return HttpResponse(str(twiml_response))

django_defaults/templates/add_contact.html
{% load crispy_forms_tags %}
<hr>
<h3>Add Contact</h3>

<div class="row">
    <div class="col-md-12">
        {% crispy form %}
    </div>
</div>

django_defaults/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Contacts manager written in Django.">
    <meta name="author" content="Matt Makai">

    <title>PyContacts in Django</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <style>
        .space-top {margin-top: 10px;}
    </style>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    {% include "top-bar.html" %}
    <div class="container-fluid">
      <div class="row">
        {% include "sidebar.html" %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %}{% endblock %}
        </div>
      </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>

django_defaults/templates/contacts.html
{% extends "base.html" %}

{% block content %}
  <h2 class="sub-header">My Contacts</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>First</th>
          <th>Last</th>
          <th>Phone Number</th>
          <th>Delete</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for contact in contacts %}
            <tr>
              <td>{{ contact.first_name }}</td>
              <td>{{ contact.last_name }}</td>
              <td>{{ contact.phone_number }}</td>
              <td><a href="{% url 'core:delete-contact' contact.id %}" class="btn btn-danger">X</a></td>
              <td><a href="{% url 'core:call-contact' contact.id %}">Call now!</a></td>
            </tr>
        {% empty %}
            <tr>
                <td>No contacts found.</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% include "add_contact.html" %}
{% endblock %}

django_defaults/templates/partials/_formhelpers.html
{% macro render_field(field) %}
<dt style="text-align: left;" class="admin-field">{{ field.label }}</dt>
    {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
                <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <dd>{{ field(class_="form-control", **kwargs)|safe }}
    </dd>
{% endmacro %}

django_defaults/templates/sidebar.html
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
      <li class="active"><a href="#">Contacts <span class="sr-only">(current)</span></a></li>
  </ul>
</div>

django_defaults/templates/top-bar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="https://github.com/makaimc/compare-python-web-frameworks">PyContacts (Django Defaults Edition)</a>
    </div>
  </div>
</nav>